Fix test not working in AOT because of problematic Xunit Assert.Equal
Assert.Equal for sequences from Xunit uses reflection internally
— even though it is not necessary, arguably it is a bug.

Wrote our own replacement for that method.

The error message before this fix:

NotSupportedException: 'Xunit.Sdk.CollectionTrackerExtensions.AsTracker[System.Boolean](System.Collections.Generic.IEnumerable`1[System.Boolean])' is missing native code. MethodInfo.MakeGenericMethod() is not compatible with AOT compilation. Inspect and fix AOT related warnings that were generated when the app was published. For more information see https://aka.ms/nativeaot-compatibility
    at System.Reflection.Runtime.MethodInfos.RuntimeNamedMethodInfo`1.GetUncachedMethodInvoker(RuntimeTypeInfo[], MemberInfo) + 0x2a
    at System.Reflection.Runtime.MethodInfos.RuntimeNamedMethodInfo`1.MakeGenericMethod(Type[]) + 0x191
    at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey, Func`2) + 0xa0
    at Xunit.Sdk.CollectionTrackerExtensions.AsTracker(IEnumerable enumerable) + 0x129
    at Xunit.Assert.Equal[T](T, T, IEqualityComparer`1) + 0x80
    at Mallard.Tests.TestExecuteScalar.BitString() + 0x16b